name: vezem_zerno
description: "Везём Зерно - мобильное приложение грузоперевозок для заказчиков и перевозчиков."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  flutter_svg: ^2.2.3
  flutter_screenutil: ^5.9.3
  auto_route: ^10.2.3
  mask_text_input_formatter: ^2.9.0
  flutter_bloc: ^9.1.1
  appwrite: ^20.3.2
  fpdart: ^1.2.0
  get_it: ^9.1.0
  equatable: ^2.0.7
  image_picker: ^1.2.1
  shimmer: ^3.0.0
  pin_code_fields: ^8.0.1
  connectivity_plus: ^7.0.0
  internet_connection_checker_plus: ^2.9.1
  yandex_mapkit: ^4.2.1
  geolocator: ^14.0.2


  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  path: ^1.9.1
  collection: ^1.19.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  auto_route_generator: ^10.2.6
  build_runner: ^2.10.4

flutter:
  uses-material-design: true
  assets:
    - assets/launcher_icon/
    - assets/splash_screen/
    - assets/svg/
    - assets/png/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false
  image_path: "assets/launcher_icon/vezem_zerno.png"
  adaptive_icon_background: "#C08E53"
  adaptive_icon_foreground: "assets/launcher_icon/vezem_zerno.png"
  adaptive_icon_foreground_inset: 28
  remove_alpha_ios: false
  min_sdk_android: 26

flutter_native_splash:
  color: "#E2C395"
  image: assets/splash_screen/logo.png
  branding: assets/splash_screen/branding.png
  branding_mode: bottom
  branding_bottom_padding: 24
  android_12:
    image: assets/splash_screen/logoV12.png
    color: "#E2C395"
    icon_background_color: "#C08E53"
    branding: assets/splash_screen/brandingV12.png
    android: true
    ios: true
    web: false